<?php
declare(strict_types=1);
date_default_timezone_set('Asia/Seoul');
$page='admin';$titles=['admin'=>'퀸만덕 운영 관리'];
?>
<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>퀸만덕 운영 관리</title><link rel="stylesheet" href="/assets/vendor/sports-admin/vendor/remixicon.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/tokens.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/base.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/layout.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/components.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/controls.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/design-system.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/prose.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/admin-tokens.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/admin.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/admin-editor.css"><link rel="stylesheet" href="/assets/vendor/sports-admin/css/rich-editor.css"><script src="/assets/vendor/lucide.min.js" defer></script><script type="module" src="/assets/js/app.js"></script></head>
<body data-page="admin" ><a class="skip-link" href="#main">본문 바로가기</a>
<header class="workspace-header admin-topbar"><a class="workspace-brand" href="/admin/"><strong>퀸만덕</strong><span>운영 관리</span></a><div class="admin-menu-search"><label class="sr-only" for="admin-menu-search">메뉴 검색</label><input id="admin-menu-search" type="search" placeholder="업무 메뉴 검색" autocomplete="off"><div id="admin-menu-results" hidden></div></div><nav aria-label="관리자 상단 메뉴"><a class="admin-topbar-action" href="/" target="_blank" rel="noopener">사이트 보기 <i class="ri-external-link-line" aria-hidden="true"></i></a><a class="admin-topbar-action" href="/admin/?view=inquiries">문의 관리</a><details class="admin-account"><summary class="admin-topbar-action">계정<i class="ri-arrow-down-s-line" aria-hidden="true"></i></summary><div><span id="session-label"></span><button data-action="logout">로그아웃</button><button id="demo-open">관리자 설정</button></div></details></nav></header>
<main id="main" tabindex="-1"></main>
<footer class="workspace-footer"><span>퀸만덕 · 관리자</span></footer><dialog id="dialog" class="admin-dialog" aria-labelledby="dialog-title"></dialog><div id="toast" role="status" aria-live="polite"></div><noscript>이 데모는 JavaScript를 활성화해야 이용할 수 있습니다.</noscript></body></html>
