<?php
declare(strict_types=1);
date_default_timezone_set('Asia/Seoul');
$titles = ['home'=>'작은 나눔, 더 큰 변화','donate'=>'기부하기','monthly'=>'정기기부','campaigns'=>'나눔 캠페인','stories'=>'나눔 스토리','organizations'=>'함께하는 단체','about'=>'퀸만덕 소개','auth'=>'로그인','my'=>'나의 나눔','partner'=>'모금단체 센터','corporate'=>'기업 파트너 센터','admin'=>'운영 관리','design-system'=>'디자인시스템','support'=>'고객센터','search'=>'마음이 닿는 이야기 찾기'];
$ops = in_array($page,['partner','corporate','admin'],true);
?>
<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#c77991"><meta name="description" content="마음이 닿는 이야기를 만나고, 그 다음의 변화까지 함께하세요. 퀸만덕 기부 플랫폼 데모."><title><?= htmlspecialchars($titles[$page] ?? '퀸만덕') ?> · 퀸만덕</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-jp-dynamic-subset.min.css"><link rel="stylesheet" href="/assets/css/tokens.css"><link rel="stylesheet" href="/assets/css/app.css"><?php if($page==='design-system'): ?><link rel="stylesheet" href="/assets/css/design-system.css"><?php endif ?><link rel="stylesheet" href="/assets/vendor/swiper.css"><script src="/assets/vendor/lucide.min.js" defer></script><script type="module" src="/assets/js/app.js"></script></head>
<body data-page="<?= $page ?>" class="<?= $ops?'operations':'' ?>"><a class="skip" href="#main">본문 바로가기</a>
<div class="topline"><div class="container">작은 마음이 모이는 곳, 퀸만덕 <span>모든 사연과 거래는 가상 데모입니다.</span></div></div>
<header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="퀸만덕 홈"><img class="brand-logo" src="/assets/brand/logo.svg" alt="퀸만덕" width="222" height="27"></a><nav class="main-nav" aria-label="주 메뉴"><?php foreach(['donate'=>'기부하기','monthly'=>'정기기부','campaigns'=>'나눔 캠페인','stories'=>'나눔 스토리'] as $slug=>$label): ?><a href="/<?= $slug ?>/" <?= $page===$slug?'aria-current="page"':'' ?>><?= $label ?></a><?php endforeach ?></nav><div class="header-tools"><a class="icon-button" href="/search/" aria-label="검색"><i data-lucide="search"></i></a><a class="icon-button" href="/my/" aria-label="마이페이지"><i data-lucide="user-round"></i></a><a class="login-link" href="/auth/" id="session-label">로그인</a></div></div></header>
<main id="main" tabindex="-1"><div class="loading container" role="status">마음이 닿는 이야기를 불러오고 있어요…</div></main>
<footer class="site-footer"><div class="container"><div class="footer-top"><a class="brand footer-brand" href="/" aria-label="퀸만덕 홈"><img src="/assets/brand/logo2.svg" alt="퀸만덕" width="130" height="81"></a><div><a href="/about/">퀸만덕 소개</a><a href="/organizations/">함께하는 단체</a><a href="/support/">고객센터</a><a href="/support/?view=terms">이용약관</a><a href="/support/?view=privacy">개인정보 안내</a></div></div><p>작은 나눔이 모여, 더 큰 변화를 만듭니다.</p><p class="fine">본 사이트는 프론트엔드 체험용 데모입니다. 실제 기부·결제·송금은 이루어지지 않습니다.<br>소개된 단체·기업·사연·수치는 가상 예시이며, 스톡사진은 활동의 이해를 돕는 참고 이미지입니다.</p><div class="footer-bottom"><span>© 2026 QUEEN MANDEOK</span><div><a href="/partner/">모금단체 센터 ↗</a><a href="/corporate/">기업 파트너 ↗</a><a href="/admin/">관리자 ↗</a><a href="/design-system/">디자인시스템</a></div></div></div></footer>
<button class="demo-launch" id="demo-open"><i data-lucide="sliders-horizontal"></i> 데모 설정</button><dialog id="dialog" aria-labelledby="dialog-title"></dialog><div id="toast" role="status" aria-live="polite"></div><noscript>이 데모는 JavaScript를 활성화해야 이용할 수 있습니다.</noscript></body></html>
